@startuml flow
autonumber "<b>[000]"
participant "User A" as ua
participant "Unique Wallet" as uw

ua -> uw : Send Crypto X
ua -> portal : Send Transaction hash
portal -> portal : Verify Transaction Details

alt Valid Transaction
	

@enduml
